---
title: "Department of Community Development"
---

The Department of Community Development is responsible for initiatives involving housing, commercial, and industrial development of city land and managing the city's housing programs. The department headquarters is in Town Hall in the center of Hopetopia. DCD includes the Housing and Planning Agency - responsible for managing housing developments and public housing programs for low-income Hopetopians - and the Buildings and Regulations Agency - charged with reviewing proposed developments, conducting building safety inspections, and code enforcement. In general, Hopetopia, like most city governments, implement state and federal housing laws and programs alongside the city's own initiatives. All new construction proposals are reviewed by a panel of appointed engineers and lawyers in the BRA. The BRA also conducts health and safety inspections of commercial and industrial enterprises and enforces building codes and standards in residential units. The sites for both departments provide an overview of recent events with the department and their current budget operations. 
